### ISSUE TITLE
copy-edit-delete without selection

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#101]
# Groups
## Edit
Can't lock a not loaded DataModel
## Copy
The group has been copied
## Delete
The group has been deleted.

# Users
## Edit
Can't lock a not loaded DataModel
## Copy
500: Access Forbidden
## Delete
500: Access Forbidden

# Sites
## Edit
500: Access Forbidden
## Delete
The selected Site definition(s) have been deleted.

# Mail Templates
## Edit
Can't lock a not loaded DataModel
## Copy
The selected Mail Templates have been copied
## Delete
The selected Mail Templates have been deleted

**Comment by nikosdion** [comment]
Needs to be fixed in AWF, see https://github.com/akeeba/awf/issues/12  The correct message should be "Access Denied" as you're now allowed to execute this function without an item ID.

I am _not_ going to disable the toolbar buttons unless a selection is made (a la Joomla) because I find it to be unnecessary busywork. If the user cannot figure out why it's stupid to try to edit, copy, or delete _nothing_ then they should not be using Panopticon to manage any sites; they are a danger to themselves and others.

I am closing this here in favour of the AWF issue.

**Comment by brianteeman** [comment]
i should have been clearer. I am not suggesting disabling the button. Thats actually an a11y issue that is on my todo to fix in core. What I am suggesting is that the message displayed is ""no mail templates were selected". Thats actually what joomla used to do and what I plan to bring back

**Comment by nikosdion** [comment]
I am not going to implement that because it's a hard break for all other software using AWF, most notably Akeeba Backup for WordPress. I don't want to go down that road right now.

As I said, a modicum of common sense is expected from users. This is not a CMS where we can reasonably expect novice users to use it. This is a tool for advanced users and experts. Therefore, the target audience should have at the very least the common sense to understand that trying to edit, copy, or delete _absolutely nothing_ can't possibly work. I also do understand that they might do it by accident. The previous messages were confusing in this case, and would reasonably mislead a user into believing the software is broken. That's why I am replacing them with "Access Denied". I reasonably expect that someone who sees "Access Denied" will wonder why, and retry BUT this time doing it right, therefore addressing the self-inflicted problem.
