### ISSUE TITLE
Failed updates

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#114]
Before I start writing a report on this I wanted to know what is the expected behaviour when an extension update fails

**Comment by nikosdion** [comment]
Currently, it's a silent failure.

**Comment by brianteeman** [comment]
ok - that was my observation. So is it worth me reporting a few scenarios where this happened for me or not

**Comment by nikosdion** [comment]
If the extension expectedly failed to updated (wrong / missing Download Key, networking issue, etc) — no.  I already know these can happen. I am planning on implementing emails on update failures. The reason cannot be emailed to you (usually), but we can definitely email you the output from Joomla.

If the problem happened because Panopticon screwed up — yes. I need the debug log entries to understand what happened.

I also know that Panopticon will retry installing the failed updates. I have not implemented anything to stop it from doing that. If you have a scenario where this becomes a big pile of excrement hitting an industrial–sized fan I’d like to know with as much detail as possible so I have a good idea why. I need to address it on the double–fast.

**Comment by brianteeman** [comment]
You've described everything I have observed so far - so nothing extra for me to report at this time.

**Comment by nikosdion** [comment]
But you have not seen any failures from Panopticon screwing up, right? That's the only kind of issue I am blind to unless I get reports for. The other ones, well, they were pretty obvious to me from planning stage. I am just taking it slowly :)

**Comment by brianteeman** [comment]
so far that is correct.
