### ISSUE TITLE
failed backup

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#115]
I created a backup profile on my site and tested that it worked - it did
I then created a cron in panopticon to take the backup
After refresh etc Panopticon showed the backup as below
![image](https://github.com/akeeba/panopticon/assets/1296369/75d555bb-0017-4eb2-83a3-0f12965df1de)

Opened the site and went to manage backups
![image](https://github.com/akeeba/panopticon/assets/1296369/26dec060-4c5e-4aba-8a1d-a2f9798e2e73)

Then View Log
![image](https://github.com/akeeba/panopticon/assets/1296369/d4864082-7f26-4ac0-8528-7c06793269ac)

Then Analyse Log
[Akeeba Backup Debug Log (1).zip](https://github.com/akeeba/panopticon/files/12329176/Akeeba.Backup.Debug.Log.1.zip)

![image](https://github.com/akeeba/panopticon/assets/1296369/16a18ff9-4fa6-4489-9daa-7bb90f710b92)

Then back to panopticon and refreshed backup info
![image](https://github.com/akeeba/panopticon/assets/1296369/a3c308b0-975d-4cea-abbf-475acc75f4d5)

**Comment by nikosdion** [comment]
Your backup was working just fine, it just had not finished yet. Since you're trying to upload 150MiB to OneDrive it's gonna take 10-15 minutes at best. If you were trying to upload the entire file to OneDrive without using chunks, or using a too big chunk size, the backup could have timed out. A timed out backup won't be detected until you either start a new backup OR visit Akeeba Backup's control panel page.

If the backup was still running, visiting Akeeba Backup's control panel page will break it. When you visit Akeeba Backup's control panel page it marks pending backups which last ticket more than 3 minutes ago as failed.

In both cases the backup would appear failed and ALICE would report it as timing out.

## Solution

In Akeeba Backup's profile configuration go to Post-processing Engine and make sure Enable chunk upload is set to Yes. Set the Chunk size to 5 MB. Click on Save & Close. Remember, running a backup through Panopticon has the same restrictions as running a backup over the web because _you are_ running a backup over the web.

While the backup is running do not visit Akeeba Backup's control panel page.

**Comment by nikosdion** [comment]
If you are going to say something about documentation, please read https://www.akeeba.com/documentation/akeeba-backup-joomla/how-to-cloud-backup-basic-config.html first.

> Most failed uploads are caused by timeouts. PHP and your web server have time limits, i.e. the maximum time a PHP script may process data before the web server aborts it. Uploading the backup archives to cloud storage takes time, the exact amount of which depends on the size of the file and the network speed. If that time is over either time limit your backup will fail. The time limit and the bandwidth are beyond our control. The only thing you can control is the size. Many post-processing engines support chunked uploading (breaking up the uploads in smaller bits and having the remote server piece together the file) and you can change their chunk size. A chunk size of 5 or 10 MB works best in most cases. For those post-processing engines which don't have an option for chunked uploads you will have to change the Part size for split archives in the Archiver Engine options. Again, a value of 5 or 10 MB works best in most cases. This setting will split our backup archive into multiple files (same base filename, the extensions are .j01, .j02, ..., .jpa; or .j01, .j02, ..., .jps; or .z01, .z02, ..., .zip;), the maximum size of each one being the value of this setting. To restore these backups just place ALL of these files in the same directory and choose the main .jpa, .jps or .zip file: the other parts are discovered and extracted automatically.

This documentation page and https://www.akeeba.com/documentation/akeeba-backup-joomla/restoring-backups.html#general-guidelines address 90% of issues we see in support tickets.

**Comment by brianteeman** [comment]
As I said at the beginning
> I created a backup profile on my site and tested that it worked - it did

that is what created the confusion.

I will test again
