### ISSUE TITLE
Site Deleted

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#129]
What is the expected behaviour in panopticon when a connected site is removed at source?

I deleted a test site from my server but panopticon still shows it AND when i do any of the manual refresh (joomla version, php version, extensions) panopticon doesnt give any errors

**Comment by nikosdion** [comment]
From Panopticon's perspective, we cannot possibly know if the site is deleted, if it has a PHP issue (e.g. a 3PD plugin accidentally nerfed the API application), if there is an issue on our side (something broke in Panopticon), a network issue on either side (or even a severed undersea cable; _this has happened to me a few years ago_), etc. Even if DNS cannot resolve it doesn't mean that the site is necessarily deleted; mistakes causing that effect do happen.

If Panopticon treated the mere existence of these issues —in isolation or over any arbitrary amount of time— as a reason to automatically take catastrophic action (delete a site) it would be wrong and insecure. Wrong because we cannot positively know that the site no longer exists, i.e. we made a decision based on incomplete data which is about as reliable as plucking hair out of one's ass. Insecure because an attacker could conceivably “blind” the monitoring site long enough to cause Panopticon to delete its monitoring and scheduling for the affected sites (or all sites!), with everything that entails.

Instead, I trust that the user is not a moron and will remove monitoring records for the sites they have already deleted outside Panopticon.

As for errors, they are only recorded in the logs. I don't want to implement an error stack because it looks to me like a really bad idea. You're away for a week, Panopticon tries to refresh information every half hour, you end up with 336 errors for the removed site, times two because we have site information check and extension updates check. So, you come back to find this site having 672 error notifications. You can display about 5–7 errors per page on a laptop, so we're talking about at least 96 pages of errors. Since browsers try to pre-render that page in memory, your browser is very slow, unresponsive, or outright crashed. Bummer. I don't know what is the better solution to that. I know that an error stack is not.

**Comment by brianteeman** [comment]
I think the thing that really "confused" me was that when you do a manual refresh you dont get any notification that the site was unreachable
