### ISSUE TITLE
Gravatar-Link broken 404

### ISSUE THREAD

**Issue by jamfx** [akeeba/panopticon#165]
Hi,
the Gravatar-Link in Profiles is broken. 

Steps to Reproduce:
1. Login to Panopticon
2. Click on Username and click on My Profile
3. Click on Edit Avatar 
4. Land on https://de.gravatar.com/1f59005aa2fffa24cbcb876a331165c3 -> get 404

regards
Niko
PS: Would love to upload my own picture instead of Gravatar :wink:

**Comment by nikosdion** [comment]
[No, it is not](https://docs.gravatar.com/general/hash/).

This is a link to your public Gravatar profile. If you have not created a Gravatar account yet for the email address you are using with Panopticon this will be a legitimate 404, as there is no public profile.

Solution: create a Gravatar profile using the same email address you are using with Panopticon.


Note: Gravatar very recently changed to support sha-256 instead of just md5. I plan on moving to sha256 as well, but it's gonna take a while. MD5 vs SHA-256 have nothing to do with your problem, though.

**Comment by jamfx** [comment]
Great, didn't knew that :+1:
