### ISSUE TITLE
Multi-factor Authentication is Disabled on your Account

### ISSUE THREAD

**Issue by aboarken** [akeeba/panopticon#191]
Hello Nicholas,

I am access my profile but I am getting a message that "Multi-factor Authentication is disabled on your account".

There is no option to enable it. How can I do that?

![Screenshot_3](https://github.com/akeeba/panopticon/assets/18500882/1f9f5bbf-f6a5-40c3-8b42-f9803cd99ef7)

**Comment by brianteeman** [comment]
If it said "Multi factor authentication has not been set up on your account yet" would it make more sense to you?

That's what the message really means. 

You need to "add a new passkey" to enable Multi factor authentication

**Comment by aboarken** [comment]
Hello @brianteeman, thank you for the explanation. I have clicked on "add a new passkey" but its not giving me the option to scan the QR Code using the Google Authenticator, its only giving me the option to register a passkey using a device or other....unless I am not recognizing what I see :(.

**Comment by nikosdion** [comment]
Google Authenticator support is coming in version 1.0.2.

**Comment by aboarken** [comment]
@nikosdion, that is the reason why I have configured is yesterday when I have installed v1.0.2dev. But when I have removed it and reinstall back version 1.0.1...it did not show.

**Comment by nikosdion** [comment]
> But when I have removed it and reinstall back version 1.0.1...it did not show.

I don't know how to phrase this without sounding like a sarcastic jerk, considering that you have already identified the source of your non-issue, but I'll give it a try.

Since you downgraded, you are now running version 1.0.1. You understand that and we agree on that.

Support for Google Authenticator does not exist in 1.0.1. It's something I wrote after I released 1.0.1. Therefore, it makes sense that you do not see the feature that does not exist in the version you are using. I think that's common sense and the whole reason for the existence of software versions.

Since the only MFA method you have in your user account is something that Panopticon does not recognise it **disables** MFA on your user account so that you are not locked out of Panopticon.
