### ISSUE TITLE
Feature request : install extentions single / multiple sites

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#192]
Hello,
ad a feature to upload a extention to panopticon and select single / multiple / all sites to install it.

**Comment by nikosdion** [comment]
I don't see a valid use case here.

Installing an extension does not make sense. You also need to enable it (or, more usually, its sub-extensions like plugins and modules), configure it, and populate it with information. This takes two to three orders of magnitude longer than installing the extension.

Beyond that, different extension versions are typically required depending on PHP and/or Joomla! version. What happens when you select the wrong version may range from an installation error to the site breaking, the latter especially possible if you install an old extension version which predates the PHP version used on the site.

On top of that, sending binary data outside the context of a file upload is extremely likely to trigger server protection solutions, blocking Panopticon from accessing that site at all. This is not idle speculation, this is what I have observed with the Site Transfer Wizard in Akeeba Backup Professional when using the HTTP transfer mode for the backup archives. 

I see a lot of ways this kind of feature can go wrong and ZERO benefits. You think you'll save the 5 seconds it takes to go to System, Extensions, Install and drag a file from one window to the other? You don't, really. You've spent much more logging into Panopticon, selecting sites, uploading the extension file, and trying to solve all the connectivity issues that pushing a large binary file entails. And you still have to log into each and every site to configure the extension.

The only use case where it would marginally make sense is delivering updates BUT this is what integrating with extensions updates is for. If you have an extension which needs updates but does not have an update site your problem is that the extension does not have an update site, which is usually a custom extension, yes? You need to solve that problem with your extension. You CAN have a publicly accessible update site for an extension which restricts downloads only to those with a key. This is exactly how all paid extensions work. For example, here's the update stream for Akeeba Backup Professional: https://cdn.akeeba.com/updates/pkgakeebapro.xml  It is publicly accessible but the downloads are not. I do the same for all the custom extensions running on my sites.

So, this sounds like a "faster horse" situation: a bad feature which only serves to marginally improve a bad worfklow without addressing the real, underlying issue.

If you have a different use case, please tell me.

**Comment by johanpeters** [comment]
Hello @nikosdion .. your response makes a lot of sense reading it.
the trigger for me was the feature on mysites.guru and watchful.. that's all.

security first.. i agree.. case / feature request closed..
