### ISSUE TITLE
Error 403: Sites deleted by one user cannot be created by another

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#197]
How to reproduce the error:
- create an example.com site with user A
- delete the example.com site with user A
- log in with user B and create the example.com site

I get errors:
**There was an unrecoverable error
The server returned the following error:
403 — Access Denied**

**Comment by nikosdion** [comment]
This is not the case. If the site is deleted you are not prevented from re-adding it.

There are two cases, though, where something _similar_ can be reproduced, but it is in both cases the expected behaviour:

If you have _unpublished_ a site nobody else, including you, can create another site with the same domain name and path. This is intentional. It prevents double entries.

If you have created a user who only has the Administrator privilege, but not the View privilege, they cannot create _any_ site. This is also intentional. No user is allowed to create a site they cannot later view. You would need to also add the View, or Edit Own privilege to allow the user to view the site they are about to create. Then, they will be able to create a site.

**Comment by morphinestyle** [comment]
Nicholas I confirm the problem but "change the title of this issue": **it is NON superusers who are unable to create sites.**

In past tests I did a test with the same site, deleting it with the Superuser account and trying to create it later with a NON superuser user account without success.

I managed to insert the deleted sites again without problems, but only with a superuser account.
**While NON superuser accounts receive a "403 error - Access Denied" even with the "ADD OWN" and "EDIT OWN" options enabled when attempting to add a site.**

**Comment by nikosdion** [comment]
As I already told you:

> If you have created a user who only has the Administrator privilege, but not the View privilege, they cannot create any site. This is also intentional. No user is allowed to create a site they cannot later view. You would need to also add the View, or Edit Own privilege to allow the user to view the site they are about to create. Then, they will be able to create a site.
