### ISSUE TITLE
feature request: make update check / update installation 

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon#209]
would be nice to have a update feature of the panopticon.
currently updates needs to be downloaded, upload, extract , clear cache etc.
and manualy check if there is a update available.

would be nice to have a check inside paoopticon with the option to update to latest version.
if possible include a backup / restore to previous version of something goes wrong with update.

**Comment by nikosdion** [comment]
The updater is already part of Panopticon. The whole thing about clearing the cache was an issue that has been fixed since 1.0.2. Of course we cannot go back in time, so you will only get the update notifications for 1.0.3 whenever it's released. Do keep in mind that we're using a completely different update method with Panopticon than we have ever done with any of our software, and something we have not seen anyone else doing either. That's why there's a bit of a rough start here.

Regarding backing up and restoring, you can of course use Akeeba Solo. The free of charge Core version will do just fine. It would not make sense duplicating an existing product of ours inside Panopticon. Back everything up except the tmp and cache folder contents.

**Comment by nikosdion** [comment]
There was, indeed, two things missing that I didn't catch when I closed this issue yesterday.

When you are up-to-date there was no way to force-reload the update information. You also didn't see any visible link to the update page. I am addressing both right now.
