### ISSUE TITLE
No emails are sent

### ISSUE THREAD

**Issue by Martin511** [akeeba/panopticon#226]
I´m running version 1.0.2.
I have set global configuration to "Send email" when updates are found.
But no email is sent on updates. Not on Joomla updates and also not on extension updates.

Edit: Sorry, wrong. E-Mails are sent but they come hourly.
I would suggest to send them daily, what in my opinion is enough.
Additionally I would prefer for admins to get **one** e-mail daily containing a list of all sites with updates instead of a big number of emails for _each_ listed site (of course depending on the number of listed sites).

**Comment by nikosdion** [comment]
Just to clarify: did the updates show up after you enabled the emails? I am asking because the trigger condition is “is the latest version available different than the previously latest version available?”.

As for the aggregate email, this won't happen right now because of the aforementioned trigger. This trigger can only be calculated when we are checking for updates. At any later point in time we don't know if a "new" version has been found. Therefore, we'd end up sending an email for the same update over and over again. In the future, when https://github.com/akeeba/panopticon/issues/220 is implemented, we can revisit this. The whole point of #220 is that there will be a log. We can, therefore, query the various “update found” entries for the sites each user has access to and construct an aggregate email if one is needed to be sent.

**Comment by Martin511** [comment]
> Just to clarify: did the updates show up after you enabled the emails?
No, I enabled the emails for extensions after there were new updates.

**Comment by nikosdion** [comment]
In this case it makes absolute sense that you did not receive any emails. The trigger event (new version found) has not happened yet.

There was a reason for this change in 1.0.2.

The original code in 1.0.0 and 1.0.1 would send you an email every time an extensions update check ran and the latest available version did not match the currently installed version. However, this had a small drawback you may have spotted: the update check for extensions runs every hour, therefore it would email you _every single hour_ for EVERY. SINGLE. EXTENSION. UPDATE on EVERY. SINGLE. SITE 💀 

In 1.0.2 I changed the code to store the last seen "latest version". If the latest version we see during the update check is the same as the last seen latest version we don't send an email (the assumption is that you already saw and/or were already sent an email). If, however, a different latest version is found _then_ we send an email.

Of course, this applies for the Email action. If there is an actual update action we do NOT send an email, we schedule an extension update instead. The same logic as above applies, with a small change when the latest version is the same as the last seen version: we check if there is an update already scheduled instead of assuming it's already scheduled.

**Comment by Martin511** [comment]
Ok, to dig a little bit deeper: can you provide a sample email template for extension updates that contains the name of the extension? Or just the string so I can configure it to my needs?

**Comment by nikosdion** [comment]
The template is already there. See screenshot.

<img width="1146" alt="Screenshot 2023-11-03 at 11 02 27" src="https://github.com/akeeba/panopticon/assets/256041/cebc74db-fe64-45e7-9528-be659d7a4ef6">

**Comment by Martin511** [comment]
> The template is already there. See screenshot.

Not in my 1.0.2.
Maybe in 1.0.3 dev?

**Comment by nikosdion** [comment]
The template has been there since 1.0.0. However, I see that the SQL may not work because of a typo, which I am fixing for 1.0.3.
