### ISSUE TITLE
Errors on systems using MariaDB 10.11 (never seen on the system with MariaDB 10.6)

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#235]
I installed Panopticon on a system with MariaDB 10.11: Panopticon generates errors that did not exist on systems using MariaDB 10.6.

I'm using PHP 8.1.24.

By clicking on **EXTENSION UPDATES** I get:
SQLSTATE[42000]: Syntax error or access violation: 1064 There is an error in the SQL syntax; check the manual that corresponds to your MariaDB server version for the correct syntax to use near '>'$.extensions.hasUpdates' = 1' on line 3

By clicking on **CORE UPDATES** I get:
SQLSTATE[42000]: Syntax error or access violation: 1064 There is an error in the SQL syntax; check the manual that corresponds to your MariaDB server version for the correct syntax to use near '>'$.core.current.version' IS NOT NULL AND `config`->'$.core.latest.version' I. .. ' on line 3

By clicking on **MY PROFILE** I get:
Access denied

EDIT:
On LOGIN i get: (with DEBUG and MAXIMUM error report)

Warning: Undefined variable $username in /home/##########/public_html/src/Controller/Login.php on line 71

UnexpectedValueException
HTTP 500
The stream or file "/home/##########/public_html/log/debug.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: Failed login
Context: {"username":"admin","error":"The stream or file \"\/home\//##########\/public_html\/log\/debug.log\" could not be opened in append mode: Failed to open stream: Permission denied\nThe exception occurred while attempting to log: Successful login\nContext: {\"username\":\"admin\"}","source":"\/home\//##########\/public_html\/vendor\/monolog\/monolog\/src\/Monolog\/Handler\/StreamHandler.php:134"}

**Comment by webgobe** [comment]
10.6.15-MariaDB,  PHP 8.2.12 same or similar errors:
EXTENSION UPDATES
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.extensions.hasUpdates' = 1' at line 3
 The problem seems to come from getIterator():
Driver->getIterator() in[ /home/lbhost/panopticon/src/Model/Extupdates.php ](https://panopticon.leftbrainhosting.net/index.php?view=extupdates)(line 78)

                        '"' . $fltPHPFamily . '.%'
                    )
                );
            }
            $iterator   = $db->setQuery($query)->getIterator();
            $extensions = [];
            if (!count($iterator))
            {
                return [];


CORE UPDATES
 same main error message: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$.core.current.version' IS NOT NULL AND `config`->'$.core.latest.version' I...' at line 3
This time seems to come from onBeforeBrowse() 

Raw->onBeforeBrowse() in[ /home/lbhost/panopticon/src/View/Coreupdates/Html.php ](https://panopticon.leftbrainhosting.net/index.php?view=coreupdates)(line 50)

            $limit = $this->getModel()->getState('limit', 50, 'int');
            $this->getModel()->setState('limit', $limit);
            $this->addTooltipJavaScript();
            return parent::onBeforeBrowse();
        }
        private function addTooltipJavaScript(): void
        {
            $js = <<< JS
```

**Comment by nikosdion** [comment]
This has been already fixed. Please look at the closed issues before submitting a new ticket or commenting “me too”.

**Comment by morphinestyle** [comment]
I just manually updated to 1.0.3 but I'm still getting the exact same errors.
I had to update manually because other errors were blocking the update.

**Comment by nikosdion** [comment]
You can't possibly get the same errors before the code which was producing the `'$.extensions.hasUpdates'` in the SQL query is not there. If you are getting the same error, you have not updated.

**Comment by nikosdion** [comment]
To explain this further, the problem was coming from https://github.com/akeeba/panopticon/blob/313eca27de3e0e65b5b02e02f79af324f3c32345/src/Model/Extupdates.php#L46 which had `jsonPointer` instead of `jsonExtract`.

The former generated a SQL WHERE clause like this `config->'$.extensions.hasUpdates' = 1`. This is JSONPath expression which is not supported by all versions of MariaDB. Which versions support it? Beats me! MariaDB does not have versioned documentation like MySQL does. Therefore, I cannot possibly tell you when this feature was introduced.

The latter generates a WHERE clause like this: `JSON_EXTRACT(config, '$.extensions.hasUpdates') = 1`. This uses the plain old JSON functions which were part of MySQL 5.5, the version of MySQL that MariaDB forked off from.

This is why I am telling you that you cannot have upgraded and have the same error. The error was referencing a JSONPath expression which is no longer generated by the model.

I believe that you can't possibly have a problem with the regular JSON methods like JSON_EXTRACT because these are used literally everywhere since version 1.0.0. If you have a server which lacks the JSON methods, well, you can't use Panopticon with it — but, I repeat, that I have not seen anything like that, nor does it make sense to see something like that given that MariaDB appears to have always had these methods built into it.

**Comment by morphinestyle** [comment]
I updated by overwriting the root with the files of the entire 1.0.3 package, even below it correctly displays version 1.0.3.

I am using:
PHP 8.1.22
MariaDB 10.11
REDIS 6.0.16

**Comment by nikosdion** [comment]
And what is the exact error message you receive?

**Comment by morphinestyle** [comment]
I currently have the following errors (errors I never had until version 1.0.2 mounted with MariaDB 11.6):

### - Administration -> My profile (but are you aware of it)
### - Overview -> Extension Updates:

42000 - SQLSTATE[42000]: Syntax error or access violation: 1064 There is an error in the SQL syntax; check the manual that corresponds to your MariaDB server version for the correct syntax to use near '>'$.extensions.hasUpdates' = 1' on line 3

**DEBUG:**

```
PDOException {#118 ▼
  +errorInfo: array:3 [♥]
}
```

Driver->getIterator()
in /home/MYDOMAIN/public_html/src/Model/Extupdates.php (line 78)
`'"' . $fltPHPFamily . '.%' ) ); } $iterator = $db->setQuery($query)->getIterator(); $extensions = []; if (!count($iterator)) { return [];`
**IT HILIGHT: $iterator   = $db->setQuery($query)->getIterator();**


### - Overview -> Major Updates:

A fatal error has occurred
The server returned the following error:

42000 - SQLSTATE[42000]: Syntax error or access violation: 1064 There is an error in the SQL syntax; check the manual that corresponds to your MariaDB server version for the correct syntax to use near '>'$.core.current.version' IS NOT NULL AND `config`->'$.core.latest.version' I. .. ' on line 3

**DEBUG:**

```
PDOException {#127 ▼
  +errorInfo: array:3 [♥]
}
```
Raw->onBeforeBrowse()
in /home/MYDOMAIN/public_html/src/View/Coreupdates/Html.php (line 50)
`$limit = $this->getModel()->getState('limit', 50, 'int'); $this->getModel()->setState('limit', $limit); $this->addTooltipJavaScript(); return parent::onBeforeBrowse(); } private function addTooltipJavaScript(): void { $js = <<< JS`
**IT HILIGHT: return parent::onBeforeBrowse();**

**Comment by nikosdion** [comment]
OK, so you are proving me right.

The issue is obvious, but has nothing to do with my code.

Clear your OPcache.
