### ISSUE TITLE
Stylesheet gets blocked

### ISSUE THREAD

**Issue by flow-motion** [akeeba/panopticon#236]
## Panopticon Template gets not loaded anymore

Hey guys, 
i installed the panotpticon on my server last week and it worked fabolous. I am now back in the office and on both machines, the css seems to get blocked. No idea why. I tried with different browsers and different machines. 
Any idea or reco?
## Environment information (please fill in this information)

* Panopticon version [e.g. 1.0]:
* PHP version [e.g. 8.2.1]:
* Browser [e.g. Chrome, Safari]:
![panopticonFailure](https://github.com/akeeba/panopticon/assets/12149866/0ec49b5a-5c88-40d8-8fac-1ee7ed40c302)

**Comment by nikosdion** [comment]
If you are installing Panopticon over HTTP and later access it over HTTPS you will get a discrepancy between how you access it (HTTPS) and its `$live_site` URL (stored as `http://...`), the latter used for generating the URL to static media files (CSS, some JavaScript files, the logo etc).

The best solution is to, of course, install Panopticon using HTTPS from the get-go.

If you forgot to do that, you can edit the `config.php` file and change `$live_site` to start with `https://` instead of `http://`.
