### ISSUE TITLE
Browser Warning when updating

### ISSUE THREAD

**Issue by flow-motion** [akeeba/panopticon#310]
Just got the notification, that panopticon 1.04. is available. 
I am actually on 1.02
So i click on "more information" and a red screen appears, containing THAT information. 

There was an unrecoverable error
The server returned the following error:

0 - Awf\Html\Helper\Basic::date(): Argument #1 ($input) must be of type string, DateTime given, called in /www/htdocs/w01bb4bf/panopticon.agentur-wachter.de/tmp/compiled_templates/26c397bf667335c2b31dce8e87d376fa24fbdd47.php on line 57
[View template: ROOT/tmp/compiled_templates/26c397bf667335c2b31dce8e87d376fa24fbdd47.php line 93, compiled from ROOT/ViewTemplates/Selfupdate/default_update.blade.php]

I have absolutley NO idea what it wants me to say :(

**Comment by nikosdion** [comment]
That was a bug fixed in 1.0.3.

[You can update to 1.0.4 manually](https://github.com/akeeba/panopticon/wiki/Updates#manual-update) by downloading the ZIP file on the new version, extract it, and upload all of the files over your existing installation.

Then, delete the `tmp/compiled_templates` folder.

That's it.

**Comment by flow-motion** [comment]
will do that   --  thanks man.
