### ISSUE TITLE
Search input styling

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#337]
Is there a reason for the tweo different styles of search inputs?

![image](https://github.com/akeeba/panopticon/assets/1296369/4c0f05fb-800f-4e0d-9189-b888ff032f87)

![image](https://github.com/akeeba/panopticon/assets/1296369/0c6238d1-b943-4234-9bf9-fd25ce675bd1)

**Comment by nikosdion** [comment]
Yes. The top one searches for extensions displayed on the page. It does not query the database, it hides and displays stuff already loaded on the page. It is applied immediately (the Search button is more or less a dummy).

The bottom one searches among sites. It is used to query the database. It is only applied when you click on the search button.

Their function is very different, which is why I styled them differently. You may not know _how_ their function differs, but just the fact they look differently will (should?) make you intuitively grasp they somehow differ.

**Comment by brianteeman** [comment]
why would I care that they work differently. to me it just looks like its a styling error and not significant of anythign else. but maybe thats just me
