### ISSUE TITLE
Images (or any HTML tag) in extension titles are rendered raw

### ISSUE THREAD

**Issue by laoneo** [akeeba/panopticon#349]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

In the extension list of a site are HTML tags from titles displayed raw.

### Reproduction instructions

Add a site with JComments extension.

### Expected behaviour

Either strip the HTML tags or render them properly.

### Actual behaviour

HTML tags are displayed as is.

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/251072/256c2dae-3b7c-44f2-ad00-5221e4094424)

### Panopticon version

Latest from Github

### PHP version

8.2.12

### Database type

MySQL

### Database version

8.x

### Browser

None

### Additional information

I have a site with JComments installed.

**Comment by nikosdion** [comment]
I would argue that what Joomla! does, rendering the extension name, author name, author URL, and description verbatim in every possible context, is insecure. All it takes is a user account which can edit language overrides and has text filters turned off, something which is unfortunately more common than you may realise. They don't need to install anything. They just need to make a malicious language override for, say, com_content. Or maybe an extension, or an API call, or anything similar which can write to the language overrides.

Try this. Create `administrator/language/overrides/en-GB.override.ini` with the following line:
```ini
COM_CONTENT_MENUS_ARTICLE_MANAGER="<script>alert('ALL YOUR BASE ARE BELONG TO US');</script>Articles"
```

Load an admin page. I am not convinced this behaviour should be allowed.

Panopticon will be used to connect to lots of sites, some of which _will_ be hacked. We don't want the hacker to be able to take over the Panopticon installation using this kind of trivial XSS. This is why we escape everything.

As for filtering tags, this won't help you much. If you only filter tags you will still have a security issue, just a far less likely one. If you strip HTML tags, well, that does work but I would also argue that Joomla! should not have let this happen in the first place. I would also argue that if you see an extension name `<script>something_malicious()</script>Foobar</script>` instead of `Foobar` is desirable as it will give you a clear warning that something has gone terribly wrong.

I think that this is something you need to discuss with JSST and the production leadership in your next meeting. If you guys officially tell me that allowing arbitrary, unfiltered HTML is a desirable Joomla! feature I am willing to do tag stripping and escaping (because I am not completely insane). If you change that behaviour to disable raw HTML then I need to change nothing.

**Comment by laoneo** [comment]
I leave it up to you, but for now Joomla accepts HTML in the extension title and I think panopticon should at least strip the tags for better usability.

**Comment by nikosdion** [comment]
I added code to strip the HTML tags before escaping the result.

**Comment by nikosdion** [comment]
You're welcome and thank you for providing the counter-perspective to my original decision :)
