### ISSUE TITLE
@media

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#355]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

This is a minor issue but I am sure the answer will be helpful to me as I progress with creating a template.

Can you explain this line or at least point to the code

https://github.com/akeeba/panopticon/blob/64a54bc1c75a1d1711ee1eeb7cd5eab61ddc402f/ViewTemplates/About/default_license.blade.php#L26

I couldnt find any other uses of @media in this way - the task I am looking to complete is to add an alt description

### Panopticon version

github

### PHP version

8.1.10

### Database type

MySQL

### Database version

8.0.30

### Browser

None

**Comment by brianteeman** [comment]
thanks

and how would I "know" this. Am I supposed to look in the blade.xml
https://github.com/akeeba/panopticon/blob/64a54bc1c75a1d1711ee1eeb7cd5eab61ddc402f/.idea/blade.xml#L31

**Comment by nikosdion** [comment]
Hm, I thought that this particular instance is self-explanatory since it refers to a file which is shipped with Panopticon. The parameters are really not important for the average frontend developer who will be only changing the filename, not trying to understand how it works. Pretty much how, let's say, in Joomla! we have some magic `Html::_('foo.bar', $whatever, false, ['bargh' => 'borgh'])` with zero explanation, without stopping site integrators from adjusting `$whatever` in their overrides.

Regarding the file, if you use PhpStorm, it enables code completion in Blade templates, listing the parameter names. I don't use Visual Studio Code, I have no idea if there is equivalent functionality. If there is, I will be happy to integrate it.
