### ISSUE TITLE
IDEA 

### ISSUE THREAD

**Issue by flow-motion** [akeeba/panopticon#363]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

No Issue - just a wish or an idea. 
What about a simple TextArea to every website, where we can insert things, like documentations, bugs, Hints for things, we need to think for, before updating... Jus a little "notes" window - directly in the dashboard- connected to the single domains. 
I would appreciate. 

### Panopticon version

1.0.5

### PHP version

8.2.

### Database type

MySQL

### Database version

8?

### Browser

None

**Comment by nikosdion** [comment]
That was fairly easy so I've already implemented it.

Caveat: notes are visible only to the people who can edit the site.

This is intentional. Notes are meant to be used for “internal” information about the site, exactly as you explained. It's not meant to be read by a client who's given view only access to their site on Panopticon just to make them feel good about being “in the loop”. 

For the vast majority of Panopticon installations this won't even be something they consider, since I've gathered most of you only use it either as a single-user, or as trusted-staff-only installations. The very, very few people who will be giving access to their clients may need to know about this, hence this note here.

Version 1.0.6 with the new feature will probably be released next week. This week I need to run some errands, and I don't want to do any release when I know I won't be in the office half of the business hours every day.
