### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by AlainRnet** [akeeba/panopticon#368]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

Is there a way to recover the file in French? Last week, I translated several strings to weblate and I understood that you no longer use it but could I retrieve the strings in FR to take them back in the PO file, please?

### Panopticon version

1.0.5

### PHP version

8.1.22

### Database type

MySQL

### Database version

5.7

### Browser

Firefox

### Browser version

116.02

**Comment by AlainRnet** [comment]
Oh, OK, thank you very much. After update, many strings were missing. I read #361 and after changing language to English, some strings are in French ?!?

**Comment by nikosdion** [comment]
I finally understand what is going on.

For this issue to occur you need the perfect trifecta:

* Your browser settings do not include English, or any other language which is 100% complete
* Your user preferences must have the language set to Use Default, or any other language which is 100% complete
* Your System Configuration must have a language which is 100% complete

In this case Panopticon loads the language communicated by the browser, and the browser defined by System Configuration. Since neither of them are 100% complete, there are some language strings which are translated by no loaded language.

I added some code at the application startup to force-load the English language strings if the default language in System Configuration is other than English (United Kingdom), therefore addressing this issue.

**Comment by AlainRnet** [comment]
Simple and concrete explanation. Thank you for your expertise!
My turn to work on a 100% FR translation ;-)

**Comment by nikosdion** [comment]
You're welcome and thank you in advance for your work :)
