### ISSUE TITLE
Bootstrap.php Issue

### ISSUE THREAD

**Issue by Memotas** [akeeba/panopticon#391]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

I translated part of the English language file to Turkish with Poedit. I uploaded the tr_TR.po file to the Panopticon/languages folder.

I created user_code/bootstrap.php with PHP code. However, the website did not work. Would you like to review it?

### Reproduction instructions

1. Go to …
2. Cicik on …
3. Scroll down to …
Go to ...

### Expected behaviour

Website did not work

### Actual behaviour

Website did not work

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/7456148/b1595cdb-754c-4b98-9d58-b1ee4953eff4)

### Panopticon version

1.0.5

### PHP version

8.2.13

### Database type

MariaDB

### Database version

10.5.23

### Browser

None

**Comment by nikosdion** [comment]
As I wrote in https://github.com/akeeba/panopticon/wiki/Translate_Existing_Language#testing-your-translation the translation testing feature will be available in 1.0.6 (that's what the current `main` branch contains, but is not yet released). Since you are on 1.0.5 the new language features do not exist yet.

I'll release 1.0.6 hopefully tomorrow.
