### ISSUE TITLE
Composer install verbosity

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#401]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Missing messages 

### Reproduction instructions

composer install

### Expected behaviour

console output displays all messageas

### Actual behaviour

as the script is running at a normal level of verbosity then any $io->debug will not be displayed but an $io->warning and $io->error will be

This was a problem when trying to work out what was going wrong as the console didnt display any issues

https://github.com/akeeba/panopticon/blob/bfde7831f90b7cfe465c4927a6b4e6bed0e7cec1/src/Composer/InstallationScript.php#L27

### Screenshots

![image](https://github.com/akeeba/panopticon/assets/1296369/d9b93f40-023f-42e5-ab92-ce6de9824cca)

With a change to warning I could immediately see my problem
![image](https://github.com/akeeba/panopticon/assets/1296369/eacb9444-c14e-44f6-96b0-4823a794f553)

### Panopticon version

github

### PHP version

8.1.3

### Database type

MySQL

### Database version

8

### Browser

None

### Additional information

Not sure of the usecase for skipping the file in the first place when running composer install

I would have done a PR to fix all of this but then spotted the same issue on other strings so maybe its better to just change the verbosity level?

**Comment by nikosdion** [comment]
This is intentional. You can increase the verbosity with the `-vv` or `-vvv` flags.

Remember that Composer – just like Panopticon's and Joomla's CLI – use Symfony Console. If you run `composer --help` it gives you the standard Symfony CLI verbosity options:
```
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

Therefore, you just need to run `composer install -vvv`

Note that this particular message is, indeed, a _debug_ message. The `version.php` file is normally created by `phing git`. The Composer script is a fallback, only intended for use [when installing Panopticon directly from Git](https://github.com/akeeba/panopticon/wiki/Install-from-Git), i.e. it's meant as an _intialiser_, not as a regular repo maintenance command.

**Comment by brianteeman** [comment]
its really annoying and you dont even get this color hilited but its your repo

**Comment by nikosdion** [comment]
I believe that the actual problem you have is not when and how Composer presents debug messages, nor whether this _particular_ message is a debug or warning. I cannot help unless you help me understand the actual problem you have.

I suspect the problem is that you are trying to manage that `version.php` file through Composer instead of using `phing build`. If you help me understand why you need to do that instead of going through Phing and why having an updated `version.php` is important in your use case I can very likely come up with a solution. Until then you will be angry at me for not solving your real issue that I don't understand, and I will be frustrated at you for not trying to help me understand your real issue.
