### ISSUE TITLE
RFC tables

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#452]
Is it intentional that a different styling is used for the main sites table compared to every other table?

![image](https://github.com/akeeba/panopticon/assets/1296369/0ceb6992-28a4-48a5-83da-29e9f95497c9)

![image](https://github.com/akeeba/panopticon/assets/1296369/4fe6194a-b6d8-4cf4-b687-3456b1dfdd09)

Specifically referring to the background and bottom border on the table head and the line below the list limit

**Comment by nikosdion** [comment]
It is absolutely intentional.

All other tables are essentially what we'd call “database record management”. They are dull information listings.

The main page (Sites Overview) is meant to be more of an informational display. It is styled and populated very differently as a result.

Your Dashboard idea took the Sites Overview to the next level of presentation, I might add. However, some people prefer a big, long, tabular presentation which is why I kept both layouts.

**Comment by brianteeman** [comment]
> All other tables are essentially what we'd call “database record management”. They are dull information listings.

all ??

![image](https://github.com/akeeba/panopticon/assets/1296369/573fa8ec-3b04-4d34-9c33-7ea467b5a47b)

**Comment by nikosdion** [comment]
I am talking about _views which are rendered as tables_.
