### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#498]
I think it would be useful if these two dropdowns indicated which is the default

![image](https://github.com/akeeba/panopticon/assets/1296369/3bd712fc-d5f7-47b9-b6a6-c5898dee7249)

![image](https://github.com/akeeba/panopticon/assets/1296369/f3e8fb0f-5645-40d0-9d9d-98e3c0a1a224)

**Comment by nikosdion** [comment]
The former; fair enough.

The latter; it's complicated. Nominally, it is what you have in System Configuration, unless overridden at the user level. But that is not important. This menu item is there in case the default (or whatever you selected in the Login page) is not a language you speak. Instead of wondering WTF to do you can click on the language icon and click on the item with that same icon to go back to something hopefully familiar to you. Or just pick a language you speak. It's the "oh, crap, I messed up my lang settings" feature. Far easier to use than memorising Nokia's numbered menu choices of twenty five years prior.

**Comment by brianteeman** [comment]
> The latter; it's complicated. 

yeah I took a look at it to try and failed badly

**Comment by nikosdion** [comment]
I would also add it would be problematic displaying the same language twice. I was originally going to not display the default option at all, but it was necessary since we don't have 100% translated languages and people would perceive the flag shown as wrong instead of realising that the translation is partial.

**Comment by brianteeman** [comment]
Confirming that this works fine
