### ISSUE TITLE
PHP File Change scanner

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#502]
I am looking at the table and its rowspan and colspan and looking at how to correctly add the scope etc.

Is there a reason that you have chosen a different table structure for displaying this information in Panopticon compared to AdminTools itself. It's kind of confusing to see the differences. Also the admintools table is much simpler with no rowspans etc

![image](https://github.com/akeeba/panopticon/assets/1296369/76355973-4a76-4a45-86de-41277ec51f4d)

![image](https://github.com/akeeba/panopticon/assets/1296369/6cb2365c-7da3-4237-81ca-49a5054ffd38)

### Summary
I propose changing the table in panopticon to that in admintools. Or am I missing something?

**Comment by nikosdion** [comment]
In Admin Tools 6 I had the rowspan and colspan. In Admin Tools 7 I was following Joomla's example of a single table head row, with the drawback that the labels by themselves made no sense (since there is no "files" mentioned in them).

I don't know what is the best solution for accessibility in this case. I have not found anything which would help me.

**Comment by brianteeman** [comment]
Its not just the single row but the different names
New => Added
Suspicious => Possible Threats

**Comment by nikosdion** [comment]
Sure, we could change that.
