### ISSUE TITLE
Adding notes doesn't work properly

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/panopticon#525]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

Adding notes to a website does not work correctly: the note is not displayed anywhere and when refreshing (save or save and close) the page, the note does not remain stored.

### Reproduction instructions

Add a note to a website
Click Save or Save and Close

### Expected behaviour

The note remains stored on the entry page.
The note can be viewed somewhere/somehow in the websites dashboard.

### Actual behaviour

The note disappeared in the entry page.
The note is not visible anywhere else.

### Panopticon version

1.1.0

### PHP version

8.2

### Database type

MariaDB

### Database version

10.11

### Browser

None

**Comment by nikosdion** [comment]
I just added this note just fine

![image](https://github.com/akeeba/panopticon/assets/256041/ec16521c-8145-4c62-a8af-56a8ec9ec676)

Notes are only displayed at the bottom of the Site Information page. They are not displayed in the Sites Overview (tabular or dashboard) views.

Remember that the green button with the arrows to the right of the Notes card is a collapse / expand button. Is it possible you have collapsed the notes, which is why you do not see them?

**Comment by Rolli1962** [comment]
Short comment - same here. Already after click on SAVE the information is deleted. Was already so with pan 1.07. Of course I have currently no use case for a note it is not important for me. Only guessing - cut it be, that a necessary table was not created with updates of panopticon?
![notes-save](https://github.com/akeeba/panopticon/assets/60449692/daf53449-ed9d-436a-b900-180c89f36443)

**Comment by brianteeman** [comment]
Fairly certain that your problem is that your db has not been updated to support the notes feature.

See 
https://github.com/akeeba/panopticon/blob/e3702a88faf66b94afe08263f23426c6d78080f0/src/schema/mysql.xml#L76-L89

**Comment by nikosdion** [comment]
@Rolli1962 If your database is not updated you should be able to go to Panopticon, Administration, Update Panopticon and click on the "Run the Post-upgrade Code" button.

**Comment by Rolli1962** [comment]
Have click on "Run the Post-upgrade Code" button. No change. Did a look on the database - the column is not there. Attached the columns of my table sites.
![sites-column](https://github.com/akeeba/panopticon/assets/60449692/30e283a1-26e5-4c1e-a311-e2cae2a9caa4)

**Comment by nikosdion** [comment]
We have been using this database updater code for 11 years (since Akeeba Backup for WordPress was released back in 2013 – yes, that was eleven years ago, I am as shocked as you are). The same code was also used on FOF 3 and 4 i.e. between 2014 and 2021 for all of our Joomla! software.

There has been exactly one reason I have ever seen this fail. Your database user does not have the privilege to run SHOW COLUMNS against the tables. Can you please check the privileges of your database user for the Panopticon database? Hint: on phpMyAdmin there's a user management link towards the top right of the main page.

**Comment by morphinestyle** [comment]
Questi sono i privilegi:

![image](https://github.com/akeeba/panopticon/assets/35969533/77e2b95e-ab73-498f-b8d9-1c170d7b2ee2)

**Comment by Rolli1962** [comment]
And I am to stupid to find settings for the rights in my phpmyadmin. It seems here do exist only one user with all rights. Even if I take a look on the versions - as least the PHP-version is not really up-to-date. It shows:
    lighttpd/1.4.55
    Datenbank-Client Version: libmysql - mysqlnd 7.4.3-4ubuntu2.18
    PHP-Erweiterung: mysqli Dokumentation curl Dokumentation mbstring Dokumentation
    PHP-Version: 7.4.3-4ubuntu2.18

**Comment by Rolli1962** [comment]
Yes, but there it is only possible to set one User with password - and not to see or set any kind of rights.

**Comment by brianteeman** [comment]
To save everyones time could you please ask your host if the user has the privilege to run SHOW COLUMNS

**Comment by Rolli1962** [comment]
> To save everyones time could you please ask your host if the user has the privilege to run SHOW COLUMNS

Have asked my provider. They want to have a error message or equal. Cause I do not have such, I gave the link to this issue.

**Comment by brianteeman** [comment]
doh
