### ISSUE TITLE
Translations with day of the week don't work (always remains English)

### ISSUE THREAD

**Issue by NetSecond** [akeeba/panopticon#625]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

In the case of translations with names of the day of the week, these are not translated, they remain in English.

Example (English/German):

String EN:
Joomla! %s receives security updates and bug fixes until %s. It will become End-of-Life and superseded by a new minor version on %s.

String DE:
Joomla! %s erhält Sicherheitsupdates und Fehlerbehebungen bis %s. Es wird End-of-Life und wird am %s durch eine neue Nebenversion ersetzt.

Result EN:
Joomla! 5.0 receives security updates and bug fixes until Wednesday, 17. April 2024. It will become End-of-Life and superseded by a new minor version on Wednesday, 17. April 2024.

Result DE:
Joomla! 5.0 erhält Sicherheitsupdates und Fehlerbehebungen bis Wednesday, 17. April 2024. Es wird End-of-Life und wird am Wednesday, 17. April 2024 durch eine neue Nebenversion ersetzt.

In both languages you get "Wednesday".

I can´t find a part of translation for these days of week.

Any solutions ??

### Panopticon version

1.2.2

### PHP version

8.3.6

### Database type

MariaDB

### Database version

??

### Browser

Edge

**Comment by nikosdion** [comment]
The localisation of days of the week and months is handled by the PHP locale.

While PHP does have [`setlocale()`](https://www.php.net/setlocale), it changes the locale per process, not per thread. This means that if used with a threaded SAPI, such as mod_php for Apache, we'll end up with randomly wrong languages used when multiple people are logged in.

Another option is using the `Intl` extension for PHP. However, it's not a standard extension, and it's not activated or even available on most commercial hosting environments. Putting a hard dependency on it causes a major problem: Panopticon won't work unless this non-standard extension is enabled. This would reduce the utility of Panopticon.

Trying to have a solution which uses `intl` when available but falls back to the standard `DateTime::format` when it's not is a pain in the butt and results in unpredictable output.

Joomla handles that by doing its own date/time formatting using PHP code, however this is _dead slow_. Since we display quite a lot of dates, doing that would have a substantial performance penalty on Panopticon.

This means that the two viable options are either using `DateTime::format` even though it displays everything in English, or using the painful method of using the `intl` extension if available. I went for the former. I am not sure if I will implement the latter.

**Comment by nikosdion** [comment]
Oh, and the non-obvious caveat: using the `intl` extension _does not allow us to choose the date format_. It only supports a bunch of predefined formats, see https://www.php.net/manual/en/class.intldateformatter.php   This means it's not a drop-in replacement, which is why it's a pain in the rear.

**Comment by brianteeman** [comment]
would it be a _clever hack_ to simply use a date format that doesnt show the day or month names

**Comment by nikosdion** [comment]
You can totally do that in the language files.

**Comment by NetSecond** [comment]
Ok, fine, thanks.

I found following in the language file:

`DATE_FORMAT_LC="l, d. F Y"
DATE_FORMAT_LC1="l, d. F Y"
DATE_FORMAT_LC2="l, d. F Y H:i"
DATE_FORMAT_LC3="d. F Y"
DATE_FORMAT_LC4="d.m.Y"
DATE_FORMAT_LC5="d.m.Y H:i"
DATE_FORMAT_LC6="d.m.Y H:i:s"
DATE_FORMAT_LC7="l, d. F Y H:i:s T"`

So, when there are 8 versions avalable, where in Panopticon can I select one ??

I can now change the first and second entry, they are the both versions, that showing the Day of week.
But why are there 8 versions, when I can´t select i.e. 5th one, what is ok for me ??

BTW: The days and months shoud be in german language too ?!?!
It is only a short workaround to let them shown as numbers but not the soloution ....

Is there maybe something wrong in another configuration outside Panopticon ??

In my configs on my server the time locale is set to: LC_TIME="de_DE.UTF-8"
Normally the date names are all in German ....
Only here in Panopticon it is English.

In other way I can fix this, if I write folowing line somwhere in Panopticon:
`setlocale(LC_TIME, 'de_DE.UTF8');`

But where ??

**Comment by nikosdion** [comment]
`setlocale` only works with `strftime`. I mentioned it as an alternative, not as something that would invariably work.

You can change all of the date lang strings to NOT have the full name of days of the week or months, only their numeric representation.

**Comment by NetSecond** [comment]
Ok, then we can close this issue, its not a Panopticon problem.

**Comment by NetSecond** [comment]
Closed.
