### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#66]
Maybe this is on your todo list 

![image](https://github.com/akeeba/panopticon/assets/1296369/35e8647c-2504-472c-b85e-904ea046ccab)

I expected to at a minimum see the permissions for the user in the list or at least the group. If you have 50 users I can't see any other way except from opening each one individually to find out that important information

**Comment by nikosdion** [comment]
The kind of display you are assuming works only on systems with predefined roles, where each user can belong to exactly one role (e.g. WordPress).

When you have multiple group membership you can't really display that. It works if the user belongs to a couple of groups, even though the page becomes cluttered and slightly unusable. If a user belongs to a dozen groups then the page is completely unusable. That's why Joomla, for example, displays "Multiple groups" if a user belongs to two or more groups instead of listing the groups. This approach is useless for Panopticon as you would have many users in 2 or more groups (one group per client to view sites, one group per client to manage sites).

The same applies for permissions. Remember, Joomla does not even bother pretending it can show you effective permissions except in a completely unusable matrix and only if you turn on debugging. Listing permissions in the list table would make it very cluttered and hard to read. This could be fixed with icons but a. sighted users will have to learn to decipher these hieroglyphs and b. screen reader users would be assaulted by a wall of permissions trying to navigate the table.

For what it's worth, no service I have used lists multiple group membership and/or permissions in a user list. Only those with predefined, singular roles do. This makes me think nobody else has solved this problem in a way which does not suck hard.

If you know of another way and, better yet, have examples of how it was done somewhere else please do tell me.

**Comment by brianteeman** [comment]
I agree the current Joomla approach for groups is not good. But then the panopticon approach goes too far the other way. I can easily mock up a prototype for you on codepen

I just need to build a connector so I can add a few sites to see what impact (if any) that has on the list

**Comment by nikosdion** [comment]
I came up with something which I think is as concise as it can be.

![image](https://github.com/akeeba/panopticon/assets/256041/08b7c665-fcbe-402d-8ed3-6085a54e9470)

Note that having the Super or Admin privilege essentially overrides the lesser privileges (including those granted by groups) which is why they appear by their lonesome even if you have other privileges checked.

If you have no permissions and no groups you essentially have no access, hence the No Access message in this case.

If you have no permissions, only groups, then you only see groups (but NOT the No Access messages, since you may be granted access to some sites due to your group membership).

**Comment by brianteeman** [comment]
yes thats so much better. I will try and share with you the approach I used for my synagogue CRM as I think you will like it.

PS if you get the chance I failed to use your phing scripts to build a connector

**Comment by nikosdion** [comment]
I added a documentation page for building the connectors https://github.com/akeeba/panopticon/wiki/Building-the-connectors

**Comment by brianteeman** [comment]
thx
