### ISSUE TITLE
Your site's SSL/TLS certificate has a problem

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#71]
Another scenario to consider adding to the bullet point of reasons why it doesnt work

In my case I was testing on a local laragon environment which has its own laragon.crt that you automatically add to the Trust Sotre certificate manager. I am assuming that this type of local cert is not compatible

**Comment by nikosdion** [comment]
For what it's worth, the message does say "You will need to install an SSL/TLS certificate signed by a commercial, well-known Certification Authority", so it does cover your use case: you have a self-signed certificate, not one signed by a commercial, well-known CA.

I have already thought of your use case —local dev site with self-signed TLS certificate— because I also use my own TLS certificates in the local sites I use for developing Panopticon.

Here's how to do this:

* Download the latest cacert.pem from https://curl.se/docs/caextract.html
* Open it in a text editor
* Append the contents of your custom public key
* Save
* Copy the modified `cacert.pem` file into Panopticon's `user_code` folder

Panopticon will use the new `cacert.pem` file as its trusted Certification Authorities file. Since you've added your custom public key file into it, that is also now trusted.

The reason I have not documented it? It is insanely insecure if used for _anything other than local testing_. I am wary about handing the public a loaded gun. A good number of them will point it at their foot and pull the trigger to see what happens…
