### ISSUE TITLE
Got an e-mail notification about a Joomla! RC1 update that did not happen and wasn't configured to be done 

### ISSUE THREAD

**Issue by wderuijter** [akeeba/panopticon#733]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

I've set up some of my websites to update to minor releases.
I just received this panopticon mail notification saying:
`Joomla! version 5.1.2-rc1 was installed on your site “......”. Before this change, your site was running the older version 5.1.1.` 
But the site is set to stable releases. Besides, when I check the system info, it has not been updates to 5.1.2-rc1.

### Reproduction instructions

No idea how to recreate this.

### Expected behaviour

I would expect RC version wil not be installed or mailed about.

### Actual behaviour

I received an e-mail saying the RC has been installed but infact it hasnt's.

### Screenshots

![screenshot-website-2024 07 06-16_42_42](https://github.com/akeeba/panopticon/assets/618804/b449c8dc-4cde-439c-897f-ea683b008048)

![screenshot-mail google com-2024 07 06-16_46_22](https://github.com/akeeba/panopticon/assets/618804/f5cec2d6-0c5b-49fa-b422-311768db487f)

### Panopticon version

1.1.3

### PHP version

8.2.20

### Database type

MySQL

### Database version

10.6.18

### Browser

None

**Comment by nikosdion** [comment]
As the interface **very clearly and explicitly** tells you, the Joomla update information comes from Joomla! itself.

In other words, your site's com_joomlaupdate (the Joomla! Update component, which is part of Joomla! itself) is what communicates with Joomla's update servers, and retrieves the update information. Panopticon merely reads the Joomla update information Joomla itself provides.

Panopticon DOES NOT know how to get update information to Joomla itself. This is deliberate. There are several update channels for Joomla. Even worse, Joomla 5.1 and later now use a different update framework which works completely differently to Joomla! 1.6 to 5.0 inclusive.

Joomla! did release a [5.1.2 Release Candidate 1](https://github.com/joomla/joomla-cms/releases/tag/5.1.2-rc1) two days ago. If the Joomla! Project made the mistake of making it available on one of the main channels it makes sense Joomla! found it and reported it. Every time something like that has happened in the past it has been fixed within a few hours, which would also explain why going back to your site later to see what is going on reports no update.

Therefore, I am closing this as none of our business.

**Comment by wderuijter** [comment]
Thanks for the detailed explanation, as always, @nikosdion!

> As the interface **very clearly and explicitly** tells you, the Joomla update information comes from Joomla! itself.
> 
> In other words, your site's com_joomlaupdate (the Joomla! Update component, which is part of Joomla! itself) is what communicates with Joomla's update servers, and retrieves the update information. Panopticon merely reads the Joomla update information Joomla itself provides.
> 
> Panopticon DOES NOT know how to get update information to Joomla itself. This is deliberate. There are several update channels for Joomla. Even worse, Joomla 5.1 and later now use a different update framework which works completely differently to Joomla! 1.6 to 5.0 inclusive.

I am aware of this, thank you. That's why I double checked if my sites are all on the stable release chanel before reporting this issue.

> Joomla! did release a [5.1.2 Release Candidate 1](https://github.com/joomla/joomla-cms/releases/tag/5.1.2-rc1) two days ago. If the Joomla! Project made the mistake of making it available on one of the main channels it makes sense Joomla! found it and reported it. Every time something like that has happened in the past it has been fixed within a few hours, which would also explain why going back to your site later to see what is going on reports no update.

That explains it indeed. For these specific sites it still shows the joomla rc1 update is available in the joomla backend. But I'll troubleshoot that further. 

> Therefore, I am closing this as none of our business.

Yes ofcourse, and thanks👍

**Comment by nikosdion** [comment]
A bit more information.

While Joomla! 5.1 introduced The Update Framework (TUF) for updates and removed the Testing update channel, some of the countless failure of the TUF implementation is that a. you can still use a legacy XML update channel as the source of Joomla! updates and b. any custom update channel you had in Joomla! 5.0 or earlier will persist to the new version.

If you had set up the Testing channel it will point to https://update.joomla.org/core/test/list_test.xml which tells Joomla to load update information from https://update.joomla.org/core/test/extension_test.xml. As you can see in there, the 5.1.2-rc1 release is listed. Therefore Joomla! will find it and report it to Panopticon which will dutifully install it as per your configuration.

Something the Joomla! project never told anyone is that after updating to Joomla! 5.1 you need to go to administrator, System, Update, Joomla! and click on Options. Make sure the Update Channel is any option other than Custom (depending on whether you want to see Joomla! 6.0 in about a year and a half) and click on Save & Close. This SHOULD fix problems like yours.

And I say “should” because the more I am looking into the TUF implementation, the less sense it makes to me. They were too busy spending 2 years writing the library code and zero time figuring out how to implement it in Joomla in a way that makes sense. I see massive failings. A simple SQLi can defeat it, which is contrary to their official messaging. If the one table they are storing the metadata fails, you are locked out of core and extension updates, creating a new vulnerability vector 💀 Yeah. I already have a to-do item to add features in Panopticon to fix – well, to work around – these problems on your sites, but it will take some more R&D to get there. It doesn't help that the whole mess is not documented and there is zero publicly available tooling for it. Typical Joomla!.

**Comment by wderuijter** [comment]
Thanks @nikosdion, sounds like a hassle, I had no clue!
