### ISSUE TITLE
Search and filters

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#74]
Apologies if this is a known todo

The search and filters do not appear to do anything

![image](https://github.com/akeeba/panopticon/assets/1296369/86a3ba49-df8e-4aa0-9216-ba2cc30932c3)

**Comment by nikosdion** [comment]
I assume you mean the main page. It is actually all working, search _and_ filters.

Please keep in mind that the search only searches within the titles, not the site URLs.

**Comment by brianteeman** [comment]
not working at all for me

**Comment by nikosdion** [comment]
I have no idea why. I did try all these controls before my previous reply, on three different installations on macOS, Linux (Tuxedo OS, an Ubuntu remix), and a live server on Rochen. 

Moreover, this is the same bog standard data model filtering we've been doing in AWF (e.g. Solo, Akeeba Backup for WordPress) the last ten years, and another 2 1/2 years before that in FOF 1.x and 2.x.

If your PHP session didn't work it would explain it, but you would also not be able to log in. So that line of reasoning is a bust.

Can you try logging out, clearing all cookies for the (sub)domain you've installed Panopticon, log back in and tell me if that made a difference? It's no witch doctor stuff, I promise! The idea here is to do a hard reset of your session, just in case something has gotten stuck in the session storage in a way I can't think of.

**Comment by brianteeman** [comment]
actually I am going to set it all up on my live server as getting the cron working locally seems to be a lost art. It appears to work but then doesnt. I will close this for now

**Comment by nikosdion** [comment]
About local CRON jobs.

If you are running on macOS, or Linux (including WSL2) you can always run `crontab -e` on your command line terminal to edit your user's CRON job task list (a.k.a. crontab).

I am not _entirely_ sure if WSL2 keeps running in the background after you close the WSL2 terminal. If it does, the CRON service should continue running. If it's not installed, you can definitely install it, it's in the Ubuntu repos.

If you're running directly on Windows (e.g. XAMPP, WAMPserver, or even [IIS with your own server definition](https://www.dionysopoulos.me/iis-development-server-for-php-on-windows-10.html)) you can use [Windows' Task Scheduler](https://www.windowscentral.com/how-create-automated-task-using-task-scheduler-windows-10).

But, yeah, doing CRON jobs on your local machine if your local machine is Windows is a massive PITA. Microsoft chooses to make everything that much more difficult.

**Comment by brianteeman** [comment]
I am using cronnical

the logs show it working but I am not convinced

**Comment by nikosdion** [comment]
I've never heard of it or used it. I can't even find it doing a web search.

**Comment by brianteeman** [comment]
sorry typo doesnt help

https://github.com/mgefvert/Cronical

**Comment by brianteeman** [comment]
so the search works on the live server. so it was either a brian bug or a windows bug. neither of which are important
