### ISSUE TITLE
Extension Name in EMails not showing

### ISSUE THREAD

**Issue by skellenb** [akeeba/panopticon#784]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

The automated Mails beeing sent on the Wordpress Connector shows not the available Extension Name but only [EXTENSION_NAME]

### Reproduction instructions

Fresh installation, Wordpress 6.6.1, PHP 8.2.22, Connector 1.0.1

### Expected behaviour

Correct Name of Extension showing in Emails

### Actual behaviour

no change

### Screenshots

![image](https://github.com/user-attachments/assets/27f00845-257d-43a7-ae46-716eb368fd00)

### Panopticon version

1.2.1

### PHP version

8.2.22

### Database type

MariaDB

### Database version

10.6.18

### Browser

None

**Comment by nikosdion** [comment]
As I have [already explained](https://github.com/akeeba/panopticon/discussions/759#discussioncomment-10288552) you just need to replace `[EXTENSION_NAME]` with `[SOFTWARE_NAME]`.

Moreover, in 03c5eb139243fa8f3f79703f03f131bebe0339c4 I have already added a workaround which allows older email templates using `[EXTENSION_NAME]` to work correctly with WordPress sites.

As a result, I am closing this issue as “invalid” since it's already been addressed, exactly two weeks ago.
