### ISSUE TITLE
Available Updates - Part 2

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#81]
No idea how this one can be solved but it will definitely cause issues as it is right now.

panopticon lists all extensions on a site
panopticon indicates if an update site is missing

The problem is that I am assuming this information is from the joomla #_update_sites_extensions and #_update_sites tables 

Very many extensions only have a single entry so panopticon lists all the others as missing.

A really good and easy to test example is the advanced custom fields from tassos
There is only one update site
![image](https://github.com/akeeba/panopticon/assets/1296369/8a9ade9f-01e4-427e-a617-8d1e3639da8e)

and there is only one entry in the update_sites_extensions table for that update site which is for extension_id 1382
![image](https://github.com/akeeba/panopticon/assets/1296369/43c99dbc-47b7-46ae-93f9-7dcbda8b3e26)

yes you can see in this truncated screenshot there are a lot of plugins for acf
![image](https://github.com/akeeba/panopticon/assets/1296369/fc3f497b-d732-4920-bdd7-d1a47b013636)

this results in panopticon showing all of these (except for 1382) as missing update sites
![image](https://github.com/akeeba/panopticon/assets/1296369/d6579c93-0ae3-48a3-9868-0a30b5a5df76)

![image](https://github.com/akeeba/panopticon/assets/1296369/e868f548-c0a2-4b1b-ac55-d1a11c80ae84)

I have no idea what to suggest

**Comment by nikosdion** [comment]
This is a mistake of the extension developer, really.

In Tassos' case he should be using a package extension and have the update site linked to the package extension. This is also why you cannot uninstall his ACF pseudo-package cleanly. You need to uninstall all his plugins, then uninstall his framework. This is not how Joomla! extensions are supposed to be packaged ever since Joomla 1.6. There was a transition period between 1.5 and 2.5 where developers needed to support both CMS version families which meant that we couldn't use package extensions, but this has not been the case for nearly a decade now.

I will add a workaround for that, as long as it does not end up showing extensions which should not be listed.

**Comment by brianteeman** [comment]
He was not the only one. I saw the same with stuff from joomlashack.

and yes I klnow they are both doing it wrong but panopticon has to be able to cope with this

**Comment by brianteeman** [comment]
i used tassos as an example as I know Crystal uses his stuff so you might have a site to test it on

**Comment by nikosdion** [comment]
That's the plan.

**Comment by nikosdion** [comment]
Peter is doing something idiotic.

Let's take "What? Nothing!" as an example.

You install a **package** extension, `pkg_whatnothing`.

The updates he offers on his site (both the XML update file and the update ZIP file) are for the **package** extension, `pkg_whatnothing`.

And yet, he stupidly assigns the update site to the sub-extension (plg_system_whatnothing) which should not be displayed because it should not be updated directly. That's the meaning of an extension belonging to a package.

**GOOD GRIEF**! When major extension developers don't understand how Joomla! works at a fundamental level I consider it a major failure of the project as a whole. This should have been neither possible (which is a very long discussion), nor allowed (at the very least not for listing on the JED). I will try to find a workaround but, man, this is getting complicated. It's like trying to write an emulator for Win32, where every other programme was exploiting some obscure undocumented bug in the Win32 API…

I guess I have to not only write the workaround code, but also an entire chapter on my book about how the hell updates are meant to work in Joomla.

**Comment by nikosdion** [comment]
BTW, I understand developers doing that for library packages which are shared between extensions because Joomla does not have a mechanism for dependencies (which takes us back to what I've been saying for well over a decade). But doing that for the main extension is just plain wrong! The update site has to be for the extension which will be updated, not for an unrelated extensions or a sub-extension of the package being updated. I can't believe I see this crap taking place in 2023.

**Comment by brianteeman** [comment]
I see this sort of thing all the time. Guess its a good thing as it gives me work - lol

**Comment by nikosdion** [comment]
I see worse things all the time, but at least they can be justified as being something the developer couldn't have known because it was very obscure and requires knowing Joomla! very well, e.g. https://www.dionysopoulos.me/common-mistakes-writing-joomla-plugins.html

But, updates?! Which have been around for 11 years?! They are stupidly obvious. I thought Joomla! extension developers were better than WordPress' script kiddies. I guess I was wrong.

**Comment by nikosdion** [comment]
OMG it's worse than I previously thought.

It installs a package. The update site is linked to the package extension. The update XML says it is for the _plugin_ extension, but it downloads a _package_ ZIP file.

So, there is no way for Joomla to report that the package (which has the update site) actually has an update available. There is also no way for Joomla to report that the plugin will be the extension showing up as having update available.

The only way to “fix” that is showing all several **HUNDREDS** of extensions installed on the site, just in case one of them mistakenly reports an update is available even though it does not have an update site attached to it.

I cannot even show you sub-extensions' updates as the update version of the extension where the package is linked to because the package extension may contain a library which follows a different versioning scheme.

At this point I think the only sane thing to do is abandon this project altogether.

**Comment by brianteeman** [comment]
i have an idea as well - just testing it

**Comment by brianteeman** [comment]
```
SELECT
    a.name,
    a.update_site_id,
    a.location,
    b.extension_id
FROM
    n4wu3_update_sites AS a
JOIN
    n4wu3_update_sites_extensions AS b
ON
    a.update_site_id = b.update_site_id
JOIN (
    SELECT
        update_site_id,
        MIN(extension_id) AS min_extension_id
    FROM
        n4wu3_update_sites_extensions
    GROUP BY
        update_site_id
) AS c
ON
    b.update_site_id = c.update_site_id
    AND b.extension_id = c.min_extension_id;

```

**Comment by nikosdion** [comment]
The correct code to select the _additional_ extensions is

```mysql
## Mostly library extensions
SELECT DISTINCT
`use`.update_site_id
FROM bot4_updates u
         INNER JOIN bot4_update_sites_extensions `use` ON `use`.update_site_id = u.update_site_id

UNION

## Non-library extensions, usually
SELECT DISTINCT
    e.extension_id
FROM
    bot4_updates u
        INNER JOIN
    bot4_extensions e
    ON e.element = u.element and e.type = u.type and e.folder = u.folder and e.client_id = u.client_id;
```

Then select the extensions as

```mysql
SELECT `e`.`extension_id` AS `id`,
       `e`.*,
       `u`.`version`      AS `new_version`,
       `u`.`detailsurl`,
       `u`.`infourl`,
       `u`.`changelogurl`,
       `use`.`update_site_id`
FROM `bot4_extensions` AS `e`
LEFT OUTER JOIN `bot4_updates` AS `u` ON `u`.`extension_id` = `e`.`extension_id`
WHERE
(`e`.`locked` != 1 OR (`e`.`type` = 'file' AND `e`.`element` = 'joomla'))
AND (
            `e`.`package_id` = 0
        OR
            `e`.extension_id IN (...)
    )
```

Yes, sure, you can put the UNION query as a subquery into the IN() argument instead of printing out the extension IDs but it's far slower than doing two queries.

It is pretty much into the Dark Arts territory.

**Comment by brianteeman** [comment]
> The correct code to select the additional extensions is

I was trying to exclude them

**Comment by brianteeman** [comment]
"missing extensions? tell your developers to get a clue"

**Comment by nikosdion** [comment]
Pretty much 😈

**Comment by nikosdion** [comment]
OK, the insane approach works. Now I need to refine it a little bit so that broken-ass extensions can use the parent package's update site.
