### ISSUE TITLE
Download code via ZIP method not possible: VIRUS found

### ISSUE THREAD

**Issue by NetSecond** [akeeba/panopticon#828]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

When I try to download the complete code via "Download Zip", Windows Defender sounds an alarm with the message "Couldn't be downloaded - virus detected".

### Reproduction instructions

Try to download the code over "<>CODE" / "Download Zip" ....

### Expected behaviour

To download one Zip file over my browser.

### Actual behaviour

Browser refuses to download due to detected virus.

### Panopticon version

Github Code download as Zip file

### PHP version

Doesn´t matter

### Database type

MariaDB

### Database version

??

### Browser

Edge

### Browser version

Version 130.0.2849.46 (64-Bit)

### Additional information

Editing in Github no problem, only download via Zip file.

**Comment by nikosdion** [comment]
What you describe does not make any sense. I have a Windows computer I use to test stuff out, and it of course has the annoying Microsoft Windows Defender.

It **DOES NOT** tell you there is a "virus". It tells you that this file is "not commonly downloaded". It does that with most files you try to download that are not static media. Apparently, Microsoft has no qualms slandering smaller and independent third party developers; they will not block the software of big corporations that can successfully sue them. Their policy is “fuck the little guys”, so my policy is “fuck Microsoft, and the high horse it rode in on”.

Solution: use a real browser, a real antivirus, or –better yet– a **REAL OPERATING SYSTEM**.

**Comment by NetSecond** [comment]
Why so aggressive??
I was simply pointing out a problem...

> What you describe does not make any sense. I have a Windows computer I use to test stuff out, and it of course has the annoying Microsoft Windows Defender.

That doesn't make sense for you, but that was exactly the problem for me yesterday.
And instead of writing briefly that it doesn't happen to you, you get loud.

The problem has now gone away for me too and I have seen that this seems to happen more often on Github and was not a browser or antivirus problem.

> It DOES NOT tell you there is a "virus".

Yes, a virus was reported to me, nothing else!!
Unfortunately I didn't take a screenshot but it's nice that you could look at my screen....
I'm starting to feel like you think I'm stupid.

I won't comment further on your last sentence for two reasons:
1. Github is owned by Microsoft
2. It worked for years and because of a small problem on my part and because of your dislike, I certainly won't switch.

I was happy to put a lot of time into your translation leading up to your comment, but if it comes as a response to a tip about a problem, then that really dampens my enjoyment.

**Comment by nikosdion** [comment]
> Why so aggressive??

Because you accused me of either distributing malware, or being responsible for the bullshit Microsoft Windows Defender feeds you. This is not an acceptable thing to do.

> Yes, a virus was reported to me, nothing else!!

So, let me get this straight. A piece of proprietary software not under my control with a long history of lying to its users tells you an obvious lie and your first reaction is NOT to figure out what is going on with it and your system, but assume I distribute malware?

If you stopped to think for five seconds you'd have realised a very obvious fact. This is Free and Open Source Software. You can trivially inspect the code to ensure it's not malicious. You can even track all changes made to it to ensure nothing malicious crept in. Putting anything malicious in it would be obvious as much as it would be stupid.

> The problem has now gone away for me too and I have seen that this seems to happen more often on Github and was not a browser or antivirus problem.

You got a message from the Microsoft Defender SmartScreen antivirus which ONLY exists on the Microsoft Edge browser, ONLY when running on the Microsoft Windows operating system, ONLY when downloading something from Microsoft-owned GitHub.

But, somehow, you believe it's not a browser or antivirus problem. Are you insane, my good man?

>  I'm starting to feel like you think I'm stupid.

I do not assume anything about your intelligence. I will and do call you out for lack of better judgement, coming to irrational conclusions, and doubling down on unfounded accusations.

> It worked for years and because of a small problem on my part and because of your dislike, I certainly won't switch.

I know very well the problems with Windows Defender. One side of it is what I have already described. The other side of it is that every so often Microsoft screws up and Windows Defender keeps returning false positives. Since you think I am biased, how about The Register reporting on it in [2024](https://www.theregister.com/2023/03/29/microsoft_defender_url_alerts/), [2022](https://www.theregister.com/2022/09/05/windows_defender_chrome_false_positive/), and [2017](https://www.theregister.com/2017/04/03/ms_defender_bluber_false_alarm/)?

Having that in mind, I only pointed out that your problems are entirely caused by **your choice** of antivirus, browser, and Operating System. You are free to choose whatever software you want, noting that if you keep using the third party software causing problems to you that's entirely your fault and your problem.

> I was happy to put a lot of time into your translation leading up to your comment, but if it comes as a response to a tip about a problem, then that really dampens my enjoyment.

It was definitely not “a tip about a problem”. Depending on how you see it, it was either a stupid, pointless issue about something that has sod all to do with the software, or a very insulting and falsely accusatory issue. Given your response, it was the latter.

**Comment by NetSecond** [comment]
Now come back down, I never accused you of anything.
I only have this one project in Github, otherwise I would have noticed it somewhere else.

But you prefer to complain instead of simply answering or giving reasons in a level-headed manner without becoming abusive.

You're arguing once again that ignores reality.
First it wasn't a virus and now it's the Smartscreen in EDGE.
I haven't activated the smart screen filter at all.
The message came after the download when saving the zip file to my disk.
The message came from Windows, not Edge, I also tested the other browsers with the same result.
I only specified EDGE because it was a required field.
But you know everything better.

I won't go into the rest because you tend to justify things instead of concentrating on the essentials.
I made the correction to the string in the issues, but that was the last action I did for Panopticon.
I don't have time for that kind of tone and your project isn't that important to me.

It was fun but the fun is now finally over.
If you have further problems/translations with the German language, you no longer need to contact me or refer me.
