### ISSUE TITLE
string

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#83]
Panopticon is measuring how long can a CRON task run

This doesnt read right to me and I am not 100% certain what you mean

It could be
Panopticon is measuring how long a CRON task can run for before timing out
Panopticon is measuring how long a CRON task takes to run
or something else...

**Comment by nikosdion** [comment]
If you want to be pedantic about it: "Panopticon is inferring the minimum value between your server's maximum CPU usage time limit and your PHP maximum execution time (the latter is infinite if you have set up CRON jobs to run under CLI using your host's CRON daemon or Windows Scheduled Tasks). This will tell Panopticon the maximum execution time it can aim for in its CRON jobs to avoid them either timing out or having their process killed by your server."

And we've lost all users who now think that sitting back for 3' is something insanely technical (it is, but it does not involve them at all).

So, more succinctly put, "Panopticon is measuring how long can a CRON task run".

**Comment by brianteeman** [comment]
> So, more succinctly put, "Panopticon is measuring how long can a CRON task run".

which is not english ;)

Panopticon is measuring how long a CRON task can run for.

**Comment by nikosdion** [comment]
Thank you for insulting me.

**Comment by brianteeman** [comment]
wtf?

**Comment by nikosdion** [comment]
The social contract here is that I am writing messages and communicating in a language that is foreign to me, for your benefit (and I mean all of you using my software, not you personally). I expect you to reciprocate by appreciating the effort and hopefully help me improve the quality of the messages. That's why I am appreciative of and grateful for your work with the language strings.

However, when a native speaker like you replies to me with the sarcastic quip “which is not English” (sic) we have a problem. It implies you don't appreciate this effort, or trust me to communicate in English. Even though I know that's not how you meant it it's still insulting.

Put yourself in my shoes. How would you like it if you tried speaking Hebrew only to be told “this is not Hebrew” by an Israeli who doesn't speak a word of English?

In any case, the point is moot. My in-house native English speaker told me that it should read "Panopticon is measuring how long a CRON task can run". No preposition. So, um, yeah, I kinda think that the original message **WAS** English after all.
