### ISSUE TITLE
WP: will not follow more than 5 redirects

### ISSUE THREAD

**Issue by rvalitov** [akeeba/panopticon#841]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the bug

I face a problem at one of the WP websites. 
It says:
```
 Will not follow more than 5 redirects
```

I used the connection doctor. It says:
```
There was a communication error with your site.

The communication library used by Panopticon ([Guzzle HTTP](https://github.com/guzzle/guzzle)) has reported the following error:


This is an unexpected condition which may indicate a communication error we have not yet seen, a problem within Guzzle itself, a problem with the server you have installed Panopticon on, or a problem in Panopticon itself. Please search the open and closed issues [on our GitHub repository](https://github.com/akeeba/panopticon/issues?q=is%3Aissue). If nobody else has reported this, please open an issue and we will take a look.

...

GuzzleHttp\Exception\TooManyRedirectsException

Will not follow more than 5 redirects

/var/www/clients/client1/web12/web/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php:155

#0 /var/www/clients/client1/web12/web/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(88): GuzzleHttp\RedirectMiddleware->guardMax()
#1 /var/www/clients/client1/web12/web/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(73): GuzzleHttp\RedirectMiddleware->checkRedirect()
#2 /var/www/clients/client1/web12/web/vendor/guzzlehttp/promises/src/FulfilledPromise.php(48): GuzzleHttp\RedirectMiddleware->GuzzleHttp\{closure}()
#3 /var/www/clients/client1/web12/web/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#4 /var/www/clients/client1/web12/web/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run()
#5 /var/www/clients/client1/web12/web/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/clients/client1/web12/web/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/clients/client1/web12/web/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
#8 /var/www/clients/client1/web12/web/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()
#9 /var/www/clients/client1/web12/web/src/Model/Trait/SiteTestConnectionWPTrait.php(159): GuzzleHttp\Client->get()
#10 /var/www/clients/client1/web12/web/src/Model/Site.php(355): Akeeba\Panopticon\Model\Site->testConnectionWordPress()
#11 /var/www/clients/client1/web12/web/src/Controller/Sites.php(131): Akeeba\Panopticon\Model\Site->testConnection()
#12 /var/www/clients/client1/web12/web/vendor/akeeba/awf/src/Mvc/Controller.php(375): Akeeba\Panopticon\Controller\Sites->connectionDoctor()
#13 /var/www/clients/client1/web12/web/vendor/akeeba/awf/src/Mvc/DataController.php(57): Awf\Mvc\Controller->execute()
#14 /var/www/clients/client1/web12/web/src/Controller/Sites.php(64): Awf\Mvc\DataController->execute()
#15 /var/www/clients/client1/web12/web/vendor/akeeba/awf/src/Dispatcher/Dispatcher.php(125): Akeeba\Panopticon\Controller\Sites->execute()
#16 /var/www/clients/client1/web12/web/src/Dispatcher.php(36): Awf\Dispatcher\Dispatcher->dispatch()
#17 /var/www/clients/client1/web12/web/vendor/akeeba/awf/src/Application/Application.php(247): Akeeba\Panopticon\Dispatcher->dispatch()
#18 /var/www/clients/client1/web12/web/src/Application.php(430): Awf\Application\Application->dispatch()
#19 /var/www/clients/client1/web12/web/index.php(35): Akeeba\Panopticon\Application->dispatch()
#20 /var/www/clients/client1/web12/web/index.php(38): {closure}()
#21 {main}
```

However, the HTTP response on screen looks good for me, it's 200, no error:
![image](https://github.com/user-attachments/assets/86346640-dfb8-4cce-9b7d-055565a87a40)

For me it looks good, the response is OK, with proper WP data. 
Can you please help me to solve this?

### Reproduction instructions

N/A

### Expected behaviour

N/A

### Actual behaviour

N/A

### Panopticon version

1.2.2

### PHP version

8.3.12

### Database type

MariaDB

### Database version

11.3.2

### Browser

None

**Comment by nikosdion** [comment]
Sounds like a problem with your site; trying to access the API results in HTTP 3xx redirects. Why? I don't know. It's not under Panopticon's purview.

**Comment by nikosdion** [comment]
Also remember that this being a redirection issue, what would make more sense for troubleshooting purposes is the rest of the troubleshooting information, especially the HTTP Headers.

**Comment by rvalitov** [comment]
Thank you! This is the screenshot with headers. I still don't get where the redirect error comes from if the HTTP status code is 200, not 30x? This does not look suspicious to you?

![image](https://github.com/user-attachments/assets/bce74387-0de8-4a1b-b4cb-eefcd2ef2e6f)

**Comment by rvalitov** [comment]
> Sounds like a problem with your site; trying to access the API results in HTTP 3xx redirects.

How that's possible if all the logs in Panopticon show HTTP code 200? Please let me know how to investigate this?

**Comment by nikosdion** [comment]
The message does not come from the code we have written in Panopticon, it comes from Guzzle. That's the standard PHP library for doing HTTP requests. If it says there are redirects, I am far more inclined to believe it than anything else.

I also see that your site is behind CloudFlare. Have you added a page rule for `/wp-json` URLs to not be cached by CloudFlare?

Moreover, are you sure that when you access your site as REDACTED it does not redirect to https://REDACTED or https://www.REDACTED because of a .htaccess rule?

That's all I can do for you.

**Comment by rvalitov** [comment]
Well, I'm curious why it's HTTP code 300x if the output says it's 200?
![image](https://github.com/user-attachments/assets/d1739413-9bd9-4c25-ba68-2f08be00dac7)

And it shows well-formed JSON data in HTTP body. I expect that if there was an error, then the code should be 30x and the body should be empty and the headers must contain redirect information. None of that is reported by Panopticon in the doctor section. 

Sure I have redirects on all of my websites, like HTTP to HTTPS. But for all other websites with the same .htaccess everything works fine. I can also include output from curl or wget, because I'm pretty sure there's are no hidden redirects. 

> Have you added a page rule for /wp-json URLs to not be cached by CloudFlare?

Yes, it's not cached, as you can see based on the `cf-cache-status` header present on my screenshot.

I purged all caches including Cloudflare cache now. Still see the same issue.

**Comment by nikosdion** [comment]
So, you have already established the problem is with this particular site's configuration, not Panopticon. Good job.

**Comment by rvalitov** [comment]
Well not like that. I have lots of Joomla websites and Panopticon works flawless there. But for each WordPress website - it's a quest to solve. And many things do not work. This website in question is also a WordPress website. From my point of view Panopticon still lacks many things for WordPress. And I'm posting here to point it and for further improvements and bug fixes. For me this case looks like a bug. I'm asking again that how it could be a redirect problem if Panopticon shows me on the same troubleshooting page a proper HTTP 200 code and proper HTTP body response from my website? That looks like a bug to me.

**Comment by nikosdion** [comment]
First of all, in terms of software engineering and objectively speaking: WordPress is a mess. There is no separation between presentation and business logic. We're talking about fundamental software engineering principles which have existed since the 1970s. Even updating plugins and WordPress itself is an exercise in working around WordPress' bullshit approach to writing software. So, yes, there will be man things which cannot be implemented in WordPress because they are either flat out impossible, or because the amount of work is disproportionate to the utility. For example, forget about having information about Download Keys in WordPress (or Joomla! 3); that's a J4+ feature. Refreshing core files is not possible with WordPress; the way its updater works prohibits that through the API, it will output HTML in a way that cannot be addressed (unlike updating to a new version). It's absolutely ridiculous how hard they chose to make the simplest of things, and how _unstable_ these APIs are even within the same major WP version.

Also, yes, the connection doctor doesn't work very well on WordPress, see https://github.com/akeeba/panopticon/issues/807  Most likely what you see is the last request that ran to completion (unauthenticated access). I cannot know since I have no idea what the Body is.

To further complicate matters, the current state of WP drama means that I am unlikely to spend any time on Panopticon's integration with WordPress. From where I am standing, the possibilities are: a. Matt gets the boot, we resume work; b. WP becomes a de facto proprietary CMS, which I don't care supporting; c. WP gets forked. Until this mess resolves I cannot spend my free time betting on a possibly dead horse, sorry.

Coming back to your site. You have an infinite redirection issue. I don't know your site's URL, nor do I know your API key, therefore I cannot possibly help you troubleshoot it. If your site is `www.example.com` and your API key is `0123456789abcdef0123456789abcdef` you can run the following to see what is going on:

```bash
curl -X GET --location "https://www.example.com/wp-json/v1/panopticon/core/update" \
    -H "X-Panopticon-Token: 0123456789abcdef0123456789abcdef" -i -L --verbose
```

It could be something as simple as you have the wrong API key and the WP JSON API freaks out, trying to redirect you instead of giving an authentication error response.

About CloudFlare, I already told you that you need a page rule to bypass the CloudFlare cache for all `/wp-json` URLs. This is not a nice-to-have; it's a must-have. You cannot be caching API replies. That said, since you get `cf-cache-status: DYNAMIC` it appears this happens automatically, at least for some of these replies.

**Comment by rvalitov** [comment]
Thank you for your help and your work! 

I understand your position regarding the WP, frankly speaking I'm surprised that WP is so popular and is CMS number 1 in the world 😅 

Good news! I could resolve my problem with the `curl` using the URL you specified. The issue was caused by the AIO All in One SEO plugin that injected a redirect like:
```
?aiowpsec_do_log_out=1&al_additional_data=1
```

That has been discussed online and considered to be a bug, updating the plugin fixed this issue. Perhaps, this info could be helpful for others who face a similar kind of problem.

Anyway I hope the issue #807 will be fixed, so at least people like me will not get confused when they see a contradicting info with the doctor: an error at one place, and a good HTTP 200 success code with well-formed data at the other part of the screen. And that leads to a question which info is correct, or either none of both 😄 And that will help to investigate such problems ourselves, seeing a proper data, without posting new issues here!

Again thank you so much for your help and for what you're doing! 🙏
