### ISSUE TITLE
requested URL was not found on this server.

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#86]
I have done two complete installs and this problem occurred both times.

Successfully installed panopticon
Let the cron scan complete
Tested all the urls work
Added two sites
Now the following urls do not work
https://scan.brianstest.site/index.php?view=sysconfig
https://scan.brianstest.site/index.php?view=site&task=read&id=1
https://scan.brianstest.site/index.php?view=site&task=read&id=2

ALL other urls still work.
I have debug on and error reporting to maximum
Its just the regular server 404

**Comment by nikosdion** [comment]
I can access all the pages just fine which tells me that you don't really have a 404, you probably have a 500 in disguise. The reason you would see a 404 instead is that the server is trying to use a custom error page which does not exist; Apache only reports the last error, which would be the 404 of the missing custom error page.

Create a .htaccess and set the following in it:

```apache
ErrorDocument 500 "Internal Server Error"
ErrorDocument 404 "Not Found"
ErrorDocument 401 "Forbidden"
```

**Comment by nikosdion** [comment]
I forgot to say, I am also trying Panopticon on a live server (hosted with Rochen), as well as two instances on macOS and Ubuntu Server which are different to my development site. I have not seen that 404.

**Comment by brianteeman** [comment]
There is already an htaccess which is used for setting the php version so I added your suggestion.

```
<FilesMatch \.php$>
        SetHandler proxy:fcgi://brian-php81
</FilesMatch>

ErrorDocument 500 "Internal Server Error"
ErrorDocument 404 "Not Found - Nik"
ErrorDocument 401 "Forbidden"
```

Still getting a 404

![image](https://github.com/akeeba/panopticon/assets/1296369/5017c294-7bf7-453a-9b84-abcc3d31c179)

also tested with 8.2

**Comment by nikosdion** [comment]
This doesn't make sense because the index.php file does exist and the question mark separates the path from the query. Something else is happening on that host. Ask the host support to tell you why you get a 404 on what is a perfectly valid request. I suspect some hosting shenanigans are at play.

**Comment by brianteeman** [comment]
it's mod_security. Disabopled it and it all works. So asking hosts for the info from the mod_security logs

**Comment by brianteeman** [comment]
ok - all sorted now

The ModSecurity log provided the following information:

`[Thu Aug 10 13:23:07.452089 2023] [:error] [pid 2597576:tid 140324159104768] [client 176.252.49.242:30939] [client 176.252.49.242] ModSecurity: Access denied with code 404 (phase 4). Pattern match "(?:(?:ne(?:ws remote php shell injection|tworkfilemanagerphp|tsploit)|c(?:(?:99 ?(?:mad)?|100 ?) ?(web)shell|ehennemden|gi-?telnet)|php(?: ?(?:commander|shell)|-?terminal| backdoor|ftp)|SvT SheLL|WSO 2.4|WebRooT Hack Tools|\\\\b(?:r(?:emote explorer|57 ? ..." at RESPONSE_BODY. [file "/etc/httpd/modsecurity.d/modsec/50_asl_rootkits.conf"] [line "153"] [id "390149"] [rev "57"] [msg "Atomicorp.com WAF Rules: Possible remote shell or bot access denied"] [data " - n3t"] [severity "CRITICAL"] [hostname "scan.brianstest.site"] [uri "/index.php"] [unique_id "ZNS6ixenADW7LLDu4ttMjAAAQwg"], referer: https://scan.brianstest.site/index.php?view=main

They have now whitelisted the ModSec rule 390149 and it all works

Maybe something to add to the docs??

**Comment by nikosdion** [comment]
This is another fine example of an asinine rule in the [Atomicorp.com WAF Rules](https://docs.atomicorp.com/rules/waf/50_asl_rootkits.conf.html#waf-rule-id-390149). It's definitely not the only one of them. There are plenty of rules which are too broad and contain very generic words or patterns which will definitely appear in your input or output data. Knowing and managing that is the job of your host; you're paying them to provide this service.

Moreover, you pay your host to set up Atomic's WAF correctly, i.e. so that blocked requests return the _correct_ HTTP status code (403 Forbidden) per the HTTP specification so that you're not mislead in your troubleshooting. You're also paying them to make the error logs available to you so you can find our which mod_security2 rules to disable.

If your host expects third party developers to document and/or support their environment —what is their paid job, not ours—  then we expect them to pay us for doing their work for them. Fair enough? 😉

Finally, the rule number does depend on the ruleset in use. In this case, they are using a well known rule set (Atomicorp.com WAF). On other servers which don't use that, trying to disable that rule number might result in unexpected problems. So there's another reason not to document anything which can be a huge foot-gun for people to use.

**Comment by brianteeman** [comment]
My bad - I didnt know but the mod_security logs are included in the server error logs so I did have access to them all the time
