### ISSUE TITLE
Lots of update sources missing in Panopticon

### ISSUE THREAD

**Issue by pklinke** [akeeba/panopticon#864]
### Due diligence

- [X] I have searched all open and closed issues for this problem.
- [X] I have searched all open and closed discussions for this problem.
- [X] I have looked at the CHANGELOG to make sure this problem has not already been addressed.
- [X] I agree to the Code of Conduct of this repository

### Describe the issue

Today I saw, that there is the message "Update-Site fehlt" in German language, "update site is missing"  for the stored sites in panopticon for lots of extensions.
In Joomla Backend I see the sources.

### Screenshots

![image](https://github.com/user-attachments/assets/2df81698-f52b-4c7b-822d-98e2535c7561)

### Panopticon version

1.3.1

### PHP version

8.3.10

### Database type

MariaDB

### Database version

10.?

### Browser

None

**Comment by nikosdion** [comment]
Panopticon reports what Joomla! tells it. I am not the developer of these extensions. Ask its developer to address the problem. I have described the problem *AND* how Joomla! has intended developers to address it since 2010 –**fourteen years** ago, when Joomla! 1.6 was released– in https://github.com/akeeba/panopticon/wiki/Extension-With-Problematic-Updates#information-for-developers
