### ISSUE TITLE
phpfile scanner

### ISSUE THREAD

**Issue by brianteeman** [akeeba/panopticon#88]
Don't you think it would be better to give the table the same/similar ui as in the admintools component? Specifically referring to two things. View Report and scan duration.

This is what I am proposing (and happy to do a pr if you approve)

![image](https://github.com/akeeba/panopticon/assets/1296369/d9e69f42-832d-4125-b12c-5aa20c54f4d9)

Note I have also not checked with a screen reader how it handles the two rows for the files headers

**Comment by nikosdion** [comment]
On the screen sizes I've tried I could see all file columns.

**Comment by brianteeman** [comment]
Another option that I am using on my crm is to drop columns into an expandable region. For this I am using datatables.net (requires jquery but there is a vanilla version)

Hard to explain how it works so this is a quick video showing columns being removed from main view and pushed into expand region. I found this a great option to use when I have a lot of data to display.


https://github.com/akeeba/panopticon/assets/1296369/811ec9f4-532d-44f4-939a-3506de229e1b

**Comment by nikosdion** [comment]
I know datatables, we were using it in ATS. 

I think that the responsive table solution in Bootstrap is better as it allows you to visually scan a table instead of having to click to expand. 

In any case, the point is that the link to the scan is better than a button which will be hidden away one way or another.

**Comment by brianteeman** [comment]
there is no responsive table solution in bootstrap other than https://getbootstrap.com/docs/5.3/content/tables/#responsive-tables which is just adding a scroll-y

I still dont see what you mean about the button being hidden. But its your software


PS deleting the video as it has some semi-personal information

**Comment by nikosdion** [comment]
Here's a better alternative. Changing the display based on the screen size.

Desktop / medium tablet (Bootstrap breakpoint `md` and above):

<img width="1102" alt="Screenshot 2023-08-11 at 15 30 30" src="https://github.com/akeeba/panopticon/assets/256041/a7f5a9cc-eff4-4e4e-97fd-49b30ea20fc8">

Small tablet / module (Bootstrap breakpoints `xs` and `sm`):

<img width="511" alt="Screenshot 2023-08-11 at 15 31 52" src="https://github.com/akeeba/panopticon/assets/256041/c6cf69bb-bb46-4783-9e4d-2b0fd2ce4ec9">

**Comment by brianteeman** [comment]
agreed - much better - the button is so much more usable than the tiny link

**Comment by nikosdion** [comment]
Needless to say, all icons have on-touch tooltips and text to be announced by screen readers. Elements which disappear on each screen size get `display: none` to remove them from the DOM the screen readers see.

At least, that's the theory. You can test the screen reader stuff yourself.

**Comment by nikosdion** [comment]
BTW, what I did is what I was trying to describe yesterday, but I just couldn't focus long enough to explain it. I was already doing something similar (though not identical) in the backup area.

The new thing I did here is collapsing the file headers from words to icons. This was the bit I was finding annoying in small screen sizes. I had tried using [responsive tables](https://getbootstrap.com/docs/5.3/content/tables/#breakpoint-specific) but it's just scrolling the table, which I found annoying and unusable. I definitely didn't want to "hide" a View Report button off-screen which is why I had used a link.

Today I had the fresh inspiration of collapsing the headers into icons which meant that I did not have to use responsive tables, which let my mind figure out I can of course move the action button. Problem solved.

**Comment by brianteeman** [comment]
I know that if I push you hard enough you will find a solution

**Comment by nikosdion** [comment]
Just don't push beyond breaking point 😛

**Comment by brianteeman** [comment]
that is something I havent learned
